# ~/.config/starship.toml

# Use custom format
format = """
[â”Œâ”€>](bold green)$directory$username$hostname$cmd_duration$status
[â”‚](bold green)$git_branch$git_commit$git_status$docer_context$golang$julia$python$php$rust
[â””â”€>](bold green) """

right_format = "$character"
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = "[   ï€Œ   ](bold green)"
error_symbol =   "[   ï€   ](bold red)"


[directory]
truncation_length = 8
read_only = "ï ½ "

[docker_context]
symbol = "ïŒˆ "

[cmd_duration]
min_time = 500
format = "underwent [$duration](bold yellow)"
show_notifications = true
min_time_to_notify = 1000

[git_branch]
symbol = "îœ¥ "

[git_commit]
tag_disabled = false
tag_symbol = "ğŸ· "


[git_status]
conflicted = "= "
ahead = "â‡¡${count} "
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind = "â‡£${count} "
untracked = "? "
stashed = "ğŸ“¦ "
modified = "ï‘™  "
deleted = "ğŸ—‘ " 

[golang]
symbol = "î˜§ "

[julia]
symbol = "î˜¤ "

[package]
symbol = "ï£– "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[rust]
symbol = "î¨ "


[hostname]
ssh_only = false
format =  "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

